### ISSUE TITLE
dbversion of struct and rating database reset to 0 occasionally after sqlite updated

### ISSUE THREAD

**Issue by dgy18787** [cosmocode/sqlite#80] opened 2023-07-20 12:32 UTC
PHP Version: 7.4, IO limited to 1Mb/s
Dokuwiki version: 2023-04-04a "Jack Jackrum"
Detail:
1. After update the Sqlite to ver 2023-06-21, sometimes (once per 3-4 days) the struct plugin and rating plugin out of work (the struct is more frequent)
2. I cannot give the detail of how user's action impact the sqlite (people just click on pages, the registration is not enabled), but when the struct doesn't work, the page will display the alert that the plugin sqlite is not installed and other info, just the same as the post in this page: https://github.com/cosmocode/dokuwiki-plugin-struct/issues/499#issuecomment-1638424597
3. when this happened to sqlite and ratings, I have to manually check the database is sqlite panel and the problem is always the same: the dbversion is set to 0 for no reason. I have to execute UPDATE opts SET val=19 WHERE opt='dbversion' to make the plugin work again, but it will be reset to 0 again after several day I make the change.

I think I have the same issue as other people posted here: https://forum.dokuwiki.org/d/21208-updating-struct-and-sqlite-broke-my-wiki-again/9 , the following is the error log I got (part) and I think it might be useful for the issue:

2023-07-20 12:07:27
PDOException: SQLSTATE[HY000]: General error: 5 database is locked
/path/keyboard/lib/plugins/sqlite/SQLiteDB.php(433)
#0 /path/keyboard/lib/plugins/sqlite/SQLiteDB.php(433): PDO->exec('VACUUM')
#1 /path/keyboard/lib/plugins/sqlite/SQLiteDB.php(69): dokuwiki\plugin\sqlite\SQLiteDB->applyMigrations()
#2 /path/keyboard/lib/plugins/struct/helper/db.php(26): dokuwiki\plugin\sqlite\SQLiteDB->__construct('struct', '/home/lifeseao/...')
#3 /path/keyboard/lib/plugins/struct/helper/db.php(43): helper_plugin_struct_db->init()
#4 /path/keyboard/lib/plugins/struct/meta/Assignments.php(49): helper_plugin_struct_db->getDB()
#5 /path/keyboard/lib/plugins/struct/meta/Assignments.php(35): dokuwiki\plugin\struct\meta\Assignments->__construct()
#6 /path/keyboard/lib/plugins/struct/action/cache.php(50): dokuwiki\plugin\struct\meta\Assignments::getInstance()
#7 /path/keyboard/inc/Extension/EventHandler.php(80): action_plugin_struct_cache->handleCacheSchemachange(Object(dokuwiki\Extension\Event), NULL)
#8 /path/keyboard/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'BEFORE')
#9 /path/keyboard/inc/Extension/Event.php(132): dokuwiki\Extension\Event->advise_before(true)
#10 /path/keyboard/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger(Array, true)
#11 /path/keyboard/inc/Cache/Cache.php(86): dokuwiki\Extension\Event::createAndTrigger('PARSER_CACHE_US...', Object(dokuwiki\Cache\CacheRenderer), Array)
#12 /path/keyboard/inc/parserutils.php(152): dokuwiki\Cache\Cache->useCache()
#13 /path/keyboard/inc/parserutils.php(96): p_cached_output('/home/lifeseao/...', 'xhtml', 'sidebar')
#14 /path/keyboard/inc/template.php(1592): p_wiki_xhtml('sidebar', '', false)
#15 /path/keyboard/lib/tpl/dokuwiki/main.php(52): tpl_include_page('sidebar', true, true)
#16 /path/keyboard/inc/actions.php(27): include('/home/lifeseao/...')
#17 /path/keyboard/doku.php(126): act_dispatch()
#18 {main}
2023-07-20 12:07:28
dokuwiki\plugin\struct\meta\StructException: The struct plugin requires the sqlite plugin. Please install and enable it.
/path/keyboard/lib/plugins/struct/helper/db.php(47)
#0 /path/keyboard/lib/plugins/struct/meta/Assignments.php(49): helper_plugin_struct_db->getDB()
#1 /path/keyboard/lib/plugins/struct/meta/Assignments.php(35): dokuwiki\plugin\struct\meta\Assignments->__construct()
#2 /path/keyboard/lib/plugins/struct/action/cache.php(50): dokuwiki\plugin\struct\meta\Assignments::getInstance()
#3 /path/keyboard/inc/Extension/EventHandler.php(80): action_plugin_struct_cache->handleCacheSchemachange(Object(dokuwiki\Extension\Event), NULL)
#4 /path/keyboard/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'BEFORE')
#5 /path/keyboard/inc/Extension/Event.php(132): dokuwiki\Extension\Event->advise_before(true)
#6 /path/keyboard/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger(Array, true)
#7 /path/keyboard/inc/Cache/Cache.php(86): dokuwiki\Extension\Event::createAndTrigger('PARSER_CACHE_US...', Object(dokuwiki\Cache\CacheRenderer), Array)
#8 /path/keyboard/inc/parserutils.php(152): dokuwiki\Cache\Cache->useCache()
#9 /path/keyboard/inc/parserutils.php(96): p_cached_output('/home/lifeseao/...', 'xhtml', 'sidebar')
#10 /path/keyboard/inc/template.php(1592): p_wiki_xhtml('sidebar', '', false)
#11 /path/keyboard/lib/tpl/dokuwiki/main.php(52): tpl_include_page('sidebar', true, true)
#12 /path/keyboard/inc/actions.php(27): include('/home/lifeseao/...')
#13 /path/keyboard/doku.php(126): act_dispatch()
#14 {main}

**Comment by splitbrain** [comment] 2023-07-20 19:34
Thanks for the log. I already found one problem. The applyMigrations method ran always, running a VACUUM operation on every initialization which is a bit excessive.

However I still have no idea how a database version of zero would happen and have not seen it on my installations so far...

**Comment by splitbrain** [comment] 2023-07-20 19:34
Thanks for the log. I already found one problem. The applyMigrations method ran always, running a VACUUM operation on every initialization which is a bit excessive.

However I still have no idea how a database version of zero would happen and have not seen it on my installations so far...

**Comment by dgy18787** [comment] 2023-07-22 07:44
Thank you for your reply, splitbrian.
Today I updated the sqlite to 2023-07-21, and after the update the rating stop working again with error:

SQLite: SQLSTATE[HY000]: General error: 1 table ratings already exists
rating plugin sqlite initialization failed
SQLite: SQLSTATE[HY000]: General error: 1 table ratings already exists
rating plugin sqlite initialization failed

The dbversion of rating is reset to 0 again. After manually execute the dbversion update command, now it works again.

**Comment by splitbrain** [comment] 2023-07-22 17:30
@dgy18787 @impactfactory I think I found the problem and partially fixed it. The underlying issue probably still happens but should "magically" fix itself with the next request without the need for manual intervention.

Everyone previously affected by the problem, please help with debugging it further. With the new version of the sqlite plugin installed, check your error logs daily to see if the message "SQLite: Could not read dbversion from opt table. Should only happen on new plugin install" has been logged. If so, please attach the log details to this issue.

**Comment by dgy18787** [comment] 2023-07-25 11:52
@splitbrain Hello Andi, thank you for your quick response! I have updated the sqlite and enable struct again, to see if there's error logged in dokuwiki. I'll let you know if there's further update.

**Comment by dgy18787** [comment] 2023-07-30 15:12
Hi Andi,

After the recent update of sqlite, everything seems to be fine so far, I only find the following error log recorded by Dokuwiki:

2023-07-29 20:15:16
SQLite: Could not read dbversion from opt table. Should only happen on new plugin install
/path/lib/plugins/sqlite/SQLiteDB.php(464)
{
"dbname": "rating",
"exception": "PDOException",
"message": "SQLSTATE[HY000]: General error: 5 database is locked",
"code": 0
}

but no error occurs on the Struct plugin. I'll be keeping notice the issue.

**Comment by zkhuber** [comment] 2023-07-31 08:23
Hi, I get similar errors.
I couldn't use page so was nesesery to uninstall struct and sqlite. I think it's happen after update Dokuwiki.
I get this error:
2023-07-31 07:29:39	path/lib/plugins/struct/helper/db.php(60)	dokuwiki\plugin\struct\meta\StructException: The struct plugin requires the sqlite plugin. Please install and enable it.
  #0 path/lib/plugins/struct/meta/Assignments.php(49): helper_plugin_struct_db->getDB()
  #1 path/lib/plugins/struct/meta/Assignments.php(35): dokuwiki\plugin\struct\meta\Assignments->__construct()
  #2 path/lib/plugins/struct/action/cache.php(50): dokuwiki\plugin\struct\meta\Assignments::getInstance()
  #3 path/inc/Extension/EventHandler.php(80): action_plugin_struct_cache->handleCacheSchemachange()
  #4 path/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
  #5 path/inc/Extension/Event.php(132): dokuwiki\Extension\Event->advise_before()
  #6 path/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
  #7 path/inc/Cache/Cache.php(86): dokuwiki\Extension\Event::createAndTrigger()
  #8 path/inc/parserutils.php(152): dokuwiki\Cache\Cache->useCache()
  #9 path/inc/parserutils.php(96): p_cached_output()
  #10 path/inc/template.php(1592): p_wiki_xhtml()
  #11 path/lib/tpl/bootstrap3/Template.php(1440): tpl_include_page()
  #12 path/lib/tpl/bootstrap3/tpl/navbar.php(65): dokuwiki\template\bootstrap3\Template->getNavbar()
  #13 path/lib/tpl/bootstrap3/main.php(51): require_once('...')
  #14 path/inc/actions.php(27): include('...')
  #15 path/doku.php(126): act_dispatch()
  #16 {main}

After install new sqlite (22.07.2023) and struct (29.07.2023) I get error:
2023-07-31 07:51:05	path/lib/plugins/sqlite/SQLiteDB.php(418)	PDOException: SQLSTATE[HY000]: General error: 1 table schemas already exists
  #0 path/lib/plugins/sqlite/SQLiteDB.php(418): PDO->exec()
  #1 path/lib/plugins/sqlite/SQLiteDB.php(71): dokuwiki\plugin\sqlite\SQLiteDB->applyMigrations()
  #2 path/lib/plugins/struct/helper/db.php(26): dokuwiki\plugin\sqlite\SQLiteDB->__construct()
  #3 path/lib/plugins/struct/helper/db.php(49): helper_plugin_struct_db->init()
  #4 path/lib/plugins/struct/meta/PageMeta.php(22): helper_plugin_struct_db->getDB()
  #5 path/lib/plugins/struct/action/title.php(42): dokuwiki\plugin\struct\meta\PageMeta->__construct()
  #6 path/inc/Extension/EventHandler.php(80): action_plugin_struct_title->handleMeta()
  #7 path/inc/Extension/Event.php(96): dokuwiki\Extension\EventHandler->process_event()
  #8 path/inc/parserutils.php(545): dokuwiki\Extension\Event->advise_after()
  #9 path/inc/parserutils.php(299): p_render_metadata()
  #10 path/inc/common.php(266): p_get_metadata()
  #11 path/doku.php(97): pageinfo()
  #12 {main}

So need to uninstall struct. Sqlite still is installed. 
Pity because I had small library working on it.
I hope you get it to work.
Huber

**Comment by splitbrain** [comment] 2023-08-01 07:14
@zkhuber the bug wrongly reset your db version to `0` resulting in migration attempts which fail because they are unnecessary. To fix you need to manually correct your db version by running `UPDATE opts SET val=19 WHERE opt='dbversion'` in the SQLite interface of the affected plugin. The `19` refers to db version to be found in the plugin's `db/latest.version` file. `19` would be correct fro struct, other plugins will have different versions.

@dgy18787 Thank you! That confirms my suspicions about the root cause. I just added some more tweaks to the database handling. Could you please update and continue to check the logs for the mentioned error?

**Comment by zkhuber** [comment] 2023-08-01 09:16
Sorry for the stupid question. But how I can run this command? After installing struct I get error:
```
PDOException: SQLSTATE[HY000]: General error: 1 table schemas already exists
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the sqlite plugin.
More info has been written to the DokuWiki error log.
```
and I have no access to dokuwiki site. Only deleting struct give me back my site. So I must do some changes to files through FTP (in struct files or sqlite files). Error shows in: /lib/plugins/sqlite/SQLiteDB.php(418): PDO->exec()
;  path/lib/plugins/sqlite/SQLiteDB.php(71): dokuwiki\plugin\sqlite\SQLiteDB->applyMigrations()

so must write something in lines 71 and 418 in SQLiteDB.php of sqlite plugin?
When I looked for db/latest.version file so in struct is 19 in sqlite is 1.

Once more, after installing struct I have access to my site only through FTP.
So please be my light and show me the way.

**Comment by zkhuber** [comment] 2023-08-03 11:27
OK. I get it.
It was necessary delate struct, run command you wrote on struct db in sqlite interface. And after this install struct. In this way struct is accepted be dokuwiki.
For now is working. Thanks.

**Comment by splitbrain** [comment] 2023-08-17 07:44
Since I haven't received any more data, I assume this to be fixed now.

**Closed by splitbrain** 2023-08-17 07:44 UTC
